### ISSUE TITLE
[Question] Is it possible to use this mod to use a scoreboard to display the top players in their respective stats?

### ISSUE THREAD

**Issue by elhertz** [HydraheadHunter/command-statistics#2]
I've been reading that you can store statistics into a scoreboard objective but I don't think you can do what I asked
You would need to make a project that tracks a specific statistic for all the players infinitely and then show the ones with the largest number in the vanilla scoreboard. 
Does minecraft automatically sort the scoreboard? if so the only thing you would need to do is track and store the statistics from all the players. How do you do this automatically? and how resource intensive would this be?
 Thanks

edit: fix typo

**Comment by HydraheadHunter** [comment]
Yes the mod was, I hope, designed to make that particular use case as simple as I could manage.  

Say you wanted to know how much dirt players have mined.

1. Create a [scoreboard objective](https://minecraft.wiki/w/Commands/scoreboard) using `scoreboard objectives add dirt_mined dummy` to store the information in.

2. Use `statistics store @p mined dirt dirt_mined` to store every players mined.dirt stat as their dirt_mined score. Call it as often as you want scores to update.

4. Do whatever you need to do using `scoreboard objectives setdisplay` to make the scoreboard look pretty. I can't help you much here cause I don't use displays for any of my personal datapacks. You'll need to find a tutorial to follow or shamelessly copy an existing datapack.

You can refine step 2 using tags, that is: replace `@p` with `@p[tag=partipant]` will make it so only players with the "participant" tag have their stats scored.

### Project
You will only need `project`s if you want to specific certian conditions under which mining dirt does or doesn't count to the score. If you want to do so, you'll use execute to run `project start` and `project pause` moods condionitionally.

Eg, if you wanted it to only count dirt that was mined while a player was standing inside the box: `-100, -64, -100` to `100, 256, 100` you'd define the box in a predicate "in_bounds" and use these two commands to turn the project's tracking stats on and off while leaving the stats as always readable:
`execute as @p[tag=participant] as @s if predicate your_datapack:in_bounds run statistics project start @s project_name`
`execute as @p[tag=participant] as @s unless predicate your_datapack:in_bounds run statistics project pause @s project_name`

Then instead of using `statistics store ...` use `statistics project store @p project_name mined dirt dirt_mined`, to get just the dirt that was counted as mined under the specified conditions.

As for performance and resource intensitivity, that'll depend on how many players you have, how many projects your running cnoncurrently, and how often you run the functions. But, I can non-so-confidently say that it probably wont be an issue? In terms of resources uses, I pretty sure stat tracking is very light-weight. My understanding is that most resources are spent on rendering and Client-Server packet exchange, and even couple hundred more jsons to track every tick wouldn't make a dent.

**Comment by elhertz** [comment]
Wow! Thank you for the info! This should be added to the wiki, no?
Great mod, thank you again!
